### ISSUE TITLE
`sample-tester` with no arguments shows help instead of running tests

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#114]
When called with no arguments, is sample-tester supposed to run (e.g. as described in #52) or show the help documentation?

To get it to run, I have to pass `--version`

As of 0.16.0, running `$ sample-tester --version` gives me my ideal experience (it auto-detects and runs tests & I can alternatively use --help to get the help docs)

Related: #113

**Comment by vchudnov-g** [comment]
That's weird. Let me look into that.
