### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/sample-tester#149]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by hkdevandla** [comment]
@vchudnov-g , friendly ping on this. 

As an alternative-  if this repo is not in active development or not supported, instead of enabling the master protection we can just make this repo as private (and hidden).

**Comment by vchudnov-g** [comment]
Done, with one caveat: we don't have status checks set up here yet. When we do (#150), I'll add them to as required on the master branch.
