### ISSUE TITLE
[Feature Request] Store location of test plan inside manifest

### ISSUE THREAD

**Issue by dwsupplee** [googleapis/sample-tester#51]
According to [the documentation](https://sample-tester.readthedocs.io/en/stable/invoking-tester/index.html) you currently need to supply both the test plan and manifest when executing the tester.

Have you considered having the location of the target test plan live within the manifest so only one YAML document (the manifest) would need to be supplied? Perhaps we could even auto-detect if the manifest exists within the directory `sample-tester` is run from and simply execute with that. WDYT?

```sh
$ cd samples/v1
$ sample-tester gen-manifest --env php --bin php *.php --output samples.manifest.yaml
$ sample-tester
```

**Comment by beccasaurus** [comment]
`$ sample-tester` <--- I would love this to work

**Comment by beccasaurus** [comment]
https://github.com/googleapis/sample-tester/issues/52 (for the $ sample-tester with no arguments)

**Comment by beccasaurus** [comment]
> both the test plan and manifest when executing the tester

The test plans are language-agnostic and reside in googleapis/googleapis alongside the .proto files

The additional YAML file (the manifest) merely provides an index of how to invoke samples _in a particular language_ by their region tag name.

When samples are generated in a library repo, the language-agnostic test plan is also copied into the client library repo. It does not know anything about _the specific language_. If you execute `sample-tester` without the manifest, the test plan tells sample-tester to execute the "language_analyze_sentiment" sample, but it doesn't know _How to run that test_.

Each language is responsible for providing its own file to map region tags to executions.

In dynamic languages, the mapping is usually directly to 1 source file, e.g. language_analyze_sentiment.js or language_analyze_sentiment.rb (although this is not always the case and many non-generated samples are bundled together in the same source files)

For static languages, this is more critical. The file needs to map the `dotnet` or `mvn` commands for how to run each code sample, so the test plan can execute them.

**Comment by dwsupplee** [comment]
Thanks, understood!

Since it seems like the manifest is required (please correct me if I've got that wrong), my thought was that when we generate the manifest with `sample-tester` it is smart enough to pick up if there is a test plan in the directory, and if so, add its path into the manifest when it generates it so we only need one input file to the tool.

**Comment by beccasaurus** [comment]
> we generate the manifest with sample-tester

We are generating it with `sample-tester`, simply using a separate command. So you run 1 command to generate the manifest. And another command runs tests. They have different responsibilities.

> it is smart enough to pick up if there is a test plan in the directory

If we wanted it to pick up the manifest / test plans without specifying then YAML files directly, we could request the following feature, WFTY?

----
### [Feature Request] Auto-discover .manifest.yaml files

If no files with `.manifest.yaml` in their names are passed to `sample-tester`, search the current directory (recursively) for files named `*.manifest.yaml` and load them automatically.
----

And a similar feature idea _(based on this common feature in many languages' test runners!)_

----
### [Feature Request] Auto-discover .test.yaml files

If no files with `.test.yaml` in their names are passed to `sample-tester`, search the current directory (recursively) for files named `*.test.yaml` and load them automatically as test plans.
----

Might be nice to standardize on `.test.yaml` and `.manifest.yaml` for explicitness. The tool _already requires_ that manifest files be named `x.manifest.yaml` but test plans can _currently_ be named anything.

**Comment by dwsupplee** [comment]
I like the thoughts that have come out of this :), going to close this out and we can file these other two feature requests as separate issues.
