### ISSUE TITLE
[Feature Request] $ sample-tester auto-detect test plans and manifests

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#52]
### `$ sample-tester`

When `sample-tester` is called with no `*.manifest.yaml` files in the arguments, `sample-tester` should recursively pickup any `**/*.manifest.yaml` files present. If none, show an error/message.

When `sample-tester` is called with no `*.test.yaml` files in the arguments, `sample-tester` should recursively pickup any `**/*.test.yaml` files present. If none, show an error/message.

When `sample-tester` is called with no `*.test.yaml` or `*.manifest.yaml` files in the arguments, `sample-tester` should recursively pickup any `**/*.test.yaml` and `**.manifest.yaml` files present. If none, show an error/message.

When `sample-tester` is called with any `*.test.yaml` file in the arguments, `sample-tester` should not search for any additional `*.test.yaml` test plans. Only the test plans explicitly passed should be run.

When `sample-tester` is called with any `*.manifest.yaml` file in the arguments, `sample-tester` should not search for any additional `*.manifest.yaml` files. Only the manifest files explicitly passed should be run.

When `sample-tester` is called with arguments that are directories, e.g. `samples/v1/` or `dir/`, that directory should be recursively searched for both `*.test.yaml` and `*.manifest.yaml` files. If none are found in that directory, no error/message. If no test plans or manifest files are found _at all_ from the arguments, show an error/message.

### Usage examples

```
sample-tester
sample-tester samples/
sample-tester samples/v1/
sample-tester my-test.test.yaml
sample-tester my-test.test.yaml samples.manifest.yaml
```

**Comment by beccasaurus** [comment]
@vchudnov-g I updated the description based on recent conversations
/cc @dwsupplee

**Comment by beccasaurus** [comment]
I keep forgetting to pass a manifest file.

Which results in an error like the following:

```
RUNNING: Test environment: "(nolang)"
  RUNNING: Test suite: "Cloud Speech V1 samples"
    FAILED: Test case: "speech_transcribe_sync"
      | 
      | ### Test case SETUP
      | 
      | ### Test case TEST
      | CALL ERROR in stage TEST : could not resolve call: object "['(nolang)', 'speech_transcribe_sync']" not defined
      | 
      | ### Test case TEARDOWN
      | 

Tests failed
```

**Comment by vchudnov-g** [comment]
In PR #105, I neglected to cover the functionality of implicit files when nothing is passed on the command line. Re-opening, and sending out a PR to address.
