### ISSUE TITLE
Improve errors for (1) misnamed manifest file (2) missing manifest file

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#58]
(1) If I name my manifest file `manifest.yaml` and run `sample-tester test.yaml manifest.yaml` I get this:

```
ERROR:root:fatal error: KeyError('test',)

ERROR: could not run tests because 'test'

usage: sample-tester [-h] [-c CONVENTION:ARG,ARG,...] [--xunit FILE]
                     [-v {quiet,summary,detailed}] [-f] [-l {none,info,debug}]
                     [--envs TESTENV_FILTER] [--suites SUITE_FILTER]
                     [--cases CASE_FILTER] [--version] [--fail-fast]
                     ...
```

It too me working with a user about half a day to figure out why. We need to fix this :)

> Meanwhile, do we really need the file naming convention?
>
> When we change the schemas to formalize them, maybe we can ignore the file name because the YAML file will basically have a header identifying its purpose. Note for later.

(2) If you run `sample-tester test.yaml` and forget to provide the manifest file, you'll get an error like this:

```
RUNNING: Test environment: "(nolang)"
  RUNNING: Test suite: "Vision V1 Sample Tests"
    FAILED: Test case: "vision_async_batch_annotate_images"
      | 
      | ### Test case SETUP
      | 
      | ### Test case TEST
      | CALL ERROR in stage TEST : could not resolve call: object "['(nolang)', 'vision_async_batch_annotate_images']" not defined
      | 
      | ### Test case TEARDOWN
      | 

Tests failed
```

The error: `CALL ERROR in stage TEST : could not resolve call: object "['(nolang)', 'vision_async_batch_annotate_images']" not defined`

This is hard to grok and we should improve this too.

See also #52 to allow for auto-detecting the manifest, which will solve problem (2). Problem (1) should be resolved with the upcoming manifest schema changes.

/cc @dizcology @googleapis/samplegen

**Comment by vchudnov-g** [comment]
I think these issue have been addressed by #52
