### ISSUE TITLE
assert_not_contains not working for me

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/sample-tester#92]
```yaml
- assert_not_contains:
  - literal: "Example count: 0"
```

```
EXCEPTION!! ConfigError('unknown YAML directive: assert_not_contains',)
```

It's here in a test though ~ are the tests passing currently? There's no badge showing status in the README.
https://github.com/googleapis/sample-tester/blob/4656779726ee0b4567cae1bf279bb7e84ad5ea8c/examples/convention-tag/language.test.yaml#L41

But when I look at master, the file moved here and `assert_not_contains` disappeared!
https://github.com/googleapis/sample-tester/blob/master/docs/defining-tests/language.test.yaml

**Comment by vchudnov-g** [comment]
This has been changed to now be `assert_excludes` and `assert_excludes_any` to clarify the semantics.

See https://sample-tester.readthedocs.io/en/stable/defining-tests/testplan-reference.html
